### ISSUE TITLE
您好，请教一个微信抓包问题

### ISSUE THREAD

**Issue by chenpengcong** [songluyi/crawl_wechat#3]
您好，看了您博客的文章受益匪浅，但我在抓包操作上遇到点问题。
我用fiddler设置代理是可以抓到`http://mp.weixin.qq.com/mp/getmasssendmsg`这条请求，但是用wireshark却抓不到。 然后我试着打开fiddler代理，手机连上fiddler代理，再打开wireshark抓，这次wireshark可以抓到`http://mp.weixin.qq.com/mp/getmasssendmsg`
对此百思不得解，可否指点12,谢谢了

**Comment by godevpy** [comment]
1.wireshark能捕获请求的前提条件是：该请求必须通过wireshark所安装的机器。

2.而你设置fiddler代理时，手机设置wifi的代理ip和端口（如 192.168.0.123:8888），这样微信的请求会先发送到该机的8888端口，然后fiddler会转发到微信服务器，所以你开了fiddler代理时，wireshark可以抓到包

**Comment by chenpengcong** [comment]
感谢回复，可能是我描述不清楚，是这样的。

我单独用wireshark抓包的时候，手机是有连上电脑发射的wifi的，wireshark通过捕获无线网卡确实是能够捕获到手机微信发出的http请求，但和利用fiddler代理抓包不同处在于wireshark丢失了`http://mp.weixin.qq.com/mp/getmasssendmsg`这条请求

结果如图：

1. 使用fiddler代理抓包
![1](https://cloud.githubusercontent.com/assets/12814622/21338045/7d55ddc0-c6ad-11e6-8aca-226a59826602.png)


2. 不使用fiddler，手机连上电脑猎豹wifi，使用wireshark捕获网卡
![2](https://cloud.githubusercontent.com/assets/12814622/21338063/a7097d52-c6ad-11e6-9e7d-d1b8cfc117de.png)

3.开启fiddler代理，手机连上fiddler代理端口，使用wireshark捕获网卡
![3](https://cloud.githubusercontent.com/assets/12814622/21338089/d59f3fee-c6ad-11e6-963e-c4904fbf130b.png)
